remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: Duitku
description: Aplikasi  pengelolaan keuangan yang memiliki fitur input jumlah uang awal, input jangka waktu, budgeting sesuai jangka waktu, reminder untuk user jika pengeluaran melebihi budget, dan mencatat pengeluaran.

